// Code generated by "stringer -type Level"; DO NOT EDIT

package logging

import "fmt"

const _Level_name = "CriticalLevelWarningLevelInformationLevelDebugLevelExtraDebugLevel1ExtremeLevel"

var _Level_index = [...]uint8{0, 13, 25, 41, 51, 67, 79}

func (i Level) String() string {
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return fmt.Sprintf("Level(%d)", i)
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
