// Code generated by "stringer -type=DeployStatus"; DO NOT EDIT

package sous

import "fmt"

const _DeployStatus_name = "InvalidDeployStatusDeployStatusUnknownDeployStatusNotRunningDeployStatusAnyDeployStatusPendingDeployStatusActiveDeployStatusFailed"

var _DeployStatus_index = [...]uint8{0, 19, 38, 60, 75, 94, 112, 130}

func (i DeployStatus) String() string {
	if i < 0 || i >= DeployStatus(len(_DeployStatus_index)-1) {
		return fmt.Sprintf("DeployStatus(%d)", i)
	}
	return _DeployStatus_name[_DeployStatus_index[i]:_DeployStatus_index[i+1]]
}
