FROM hello-world:latest
LABEL \
  com.opentable.sous.repo_url=https://github.com/docker-library/hello-world.git \
  com.opentable.sous.repo_offset= \
  com.opentable.sous.version=1.0.7-latest \
  com.opentable.sous.revision=399583d822469c07954d94232d81db95b3176369 \
