FROM hello-world:latest
LABEL \
  com.opentable.repo=https://github.com/docker-library/hello-world.git \
  com.opentable.revision=399583d822469c07954d94232d81db95b3176369 \
  com.opentable.version=1.0.7-latest \
  com.opentable.subdir= \
